version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: cine_db
    environment:
      POSTGRES_USER: cine
      POSTGRES_PASSWORD: cine
      POSTGRES_DB: cine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cine -d cine"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
